apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-config
data:
  ocelot.json: |
    {
      "Routes": [
        {
          "UpstreamPathTemplate": "/MapDiscussion/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/MapDiscussion/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "discussion-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/DifficultyDiscussion/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/DifficultyDiscussion/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "discussion-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/User/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/User/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "user-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/Comment/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/Comment/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "comment-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/Reply/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/Reply/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "comment-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/Review/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/Review/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "comment-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/DiscussionService/metrics",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/metrics",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "discussion-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/UserService/metrics",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/metrics",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "user-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        },
        {
          "UpstreamPathTemplate": "/CommentService/metrics",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete" ],
          
          "DownstreamPathTemplate": "/metrics",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "comment-service-service",
              "Port": 8080
            }
          ],
          
          "DangerousAcceptAnyServerCertificateValidator": true
        }
      ],
      "GlobalConfiguration": {
        "BaseUrl": "http://api-gateway-service.default.svc.cluster.local"
      }
    }
    