version: '3.4'

networks:
  backend-common:

  backend-discussion:
    
  backend-user:
  
  backend-comment:


services:
  discussionservice:
    container_name: discussion-service
    image: ${DOCKER_REGISTRY-}discussionservice
    build:
      context: .
      dockerfile: DiscussionService/Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=rf-discussion
      - DB_USER=postgres
      - DB_SA_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-discussion
    ports:
      - "8003:8080"
      - "8004:8081"
    volumes:
      - ././containers/discussionservice/data/discussionservice:/app/data

  userservice:
    container_name: user-service
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=rf-user
      - DB_USER=postgres
      - DB_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-user
    ports:
      - "8005:8080"
      - "8006:8081"
    volumes:
      - ././containers/userservice/data/userservice:/app/data
        
  commentservice:
    container_name: comment-service
    image: ${DOCKER_REGISTRY-}commentservice
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    environment:
      - DB_HOST=postgres
      - DB_NAME=rf-comment
      - DB_USER=postgres
      - DB_SA_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-comment
    ports:
      - "8007:8080"
      - "8008:8081"
    volumes:
      - ././containers/commentservice/data/commentservice:/app/data

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend-common
    ports:
      - "3900:3900"
      - "8001:8080"
      - "8002:8081"
  
  rankingforum-mq:
    image: rabbitmq:3-management
    container_name: RankingForum.RabbitMQ
    hostname: rankingforum-mq
    volumes:
      - ././containers/queue/data/:/var/lib/rabbitmq
      - ././containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend-common
    ports:
      - "15672:15672"
      - "5672:5672"
    
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperStrong!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-common

volumes:
  postgres_data: