version: '3.4'

networks:
  backend-common:

  backend-discussion:
    
  backend-user:
  
  backend-comment:


services:
  discussionservice:
    container_name: discussion-service
    image: ${DOCKER_REGISTRY-}discussionservice
    build:
      context: .
      dockerfile: DiscussionService/Dockerfile
    environment:
      - DB_HOST=discussion-db
      - DB_NAME=rf-discussion
      - DB_SA_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-discussion
    ports:
      - "8003:8080"
      - "8004:8081"
    volumes:
      - ././containers/discussionservice/data/discussionservice:/app/data
  
  discussion-db:
    container_name: discussion-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperStrong!
    networks:
      - backend-discussion
    ports:
      - "39001:1433"
    volumes:
      - ././containers/discussionservice/db/discussiondb:/var/opt/mssql/data

  userservice:
    container_name: user-service
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: UserService/Dockerfile
    environment:
      - DB_HOST=user-db
      - DB_NAME=rf-user
      - DB_SA_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-user
    ports:
      - "8005:8080"
      - "8006:8081"
    volumes:
      - ././containers/userservice/data/userservice:/app/data

  user-db:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperStrong!
    networks:
      - backend-user
    ports:
      - "39002:1433"
    volumes:
      - ././containers/userservice/db/userdb:/var/opt/mssql/data
        
  commentservice:
    container_name: comment-service
    image: ${DOCKER_REGISTRY-}commentservice
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    environment:
      - DB_HOST=comment-db
      - DB_NAME=rf-comment
      - DB_SA_PASSWORD=SuperStrong!
      - RABBITMQ_HOST=rankingforum-mq
      - JWT_SECRET_KEY=DevelopmentSecretKey543523465463
    networks:
      - backend-common
      - backend-comment
    ports:
      - "8007:8080"
      - "8008:8081"
    volumes:
      - ././containers/commentservice/data/commentservice:/app/data

  comment-db:
    container_name: comment-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperStrong!
    networks:
      - backend-comment
    ports:
      - "39003:1433"
    volumes:
      - ././containers/commentservice/db/commentdb:/var/opt/mssql/data

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend-common
    ports:
      - "3900:3900"
      - "8001:8081"
      - "8002:8080"
  
  rankingforum-mq:
    image: rabbitmq:3-management
    container_name: RankingForum.RabbitMQ
    hostname: rankingforum-mq
    volumes:
      - ././containers/queue/data/:/var/lib/rabbitmq
      - ././containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - backend-common
    ports:
      - "15672:15672"
      - "5672:5672"
