version: '3.4'

networks:
  backend:



services:
  userdb:
    container_name: user-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperStrong!
    networks:
      - backend
    ports:
      - "18001:1433"

  userwebapi:
    container_name: user-api
    image: ${DOCKER_REGISTRY-}userwebapi
    build:
      context: .
      dockerfile: UserWebApi/Dockerfile
    environment:
      - DB_HOST=userdb
      - DB_NAME=user
      - DB_SA_PASSWORD=SuperStrong!
    networks:
      - backend

  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    networks:
      - backend
    ports:
      - "8001:8081"
      - "8002:8080"

