apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx
  namespace: default
spec:
  secretName: ingress-nginx
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - 'rfapi.lightai.dev'