apiVersion: apps/v1
kind: Deployment
metadata:
  name: discussion-db-deployment
  labels:
    app: discussion-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discussion-db
  template:
    metadata:
      labels:
        app: discussion-db
    spec:
      containers:
        - name: discussion-db
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: discussion-db-password

---
apiVersion: v1
kind: Service
metadata:
  name: discussion-db-service
spec:
  selector:
    app: discussion-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
