apiVersion: apps/v1
kind: Deployment
metadata:
  name: discussion-service-deployment
  labels:
    app: discussion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discussion-service
  template:
    metadata:
      labels:
        app: discussion-service
    spec:
      containers:
        - name: discussion-service
          image: lightai39/rf-discussionservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: rabbitmq-url
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: rabbitmq-port
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-user
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-pass
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: discussion-db-url
            - name: DB_NAME
              value: rf-discussion
            - name: DB_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: discussion-db-password

---
apiVersion: v1
kind: Service
metadata:
  name: discussion-service-service
spec:
  selector:
    app: discussion-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
