# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  apigateway:
    build:
      context: "G:\\DEV\\repos\\RankingForum"
      dockerfile: "ApiGateway/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "apigateway:dev"
    ports:
    - "127.0.0.1:57015:57100"
    - "127.0.0.1:57215:57300"
    volumes:
    - "C:\\Users\\Wessel van Hemert\\.nuget\\packages:/home/app/.nuget/packages"
    - "G:\\DEV\\repos\\RankingForum\\ApiGateway:/app:rw"
    - "G:\\DEV\\repos\\RankingForum:/src:rw"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2024.1.2\\Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\\
      DebuggerWorker\\JetBrains.Debugger.Worker.2024_5_20_03_19_20:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  discussionservice:
    build:
      context: "G:\\DEV\\repos\\RankingForum"
      dockerfile: "DiscussionService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "discussionservice:dev"
    ports:
    - "127.0.0.1:57016:57100"
    - "127.0.0.1:57216:57300"
    volumes:
    - "C:\\Users\\Wessel van Hemert\\.nuget\\packages:/home/app/.nuget/packages"
    - "G:\\DEV\\repos\\RankingForum\\DiscussionService:/app:rw"
    - "G:\\DEV\\repos\\RankingForum:/src:rw"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2024.1.2\\Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\\
      DebuggerWorker\\JetBrains.Debugger.Worker.2024_5_20_03_19_20:/var/opt/rider-debugger:rw"
    working_dir: "/app"
  userservice:
    build:
      context: "G:\\DEV\\repos\\RankingForum"
      dockerfile: "UserService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "userservice:dev"
    ports:
    - "127.0.0.1:57017:57100"
    - "127.0.0.1:57217:57300"
    volumes:
    - "C:\\Users\\Wessel van Hemert\\.nuget\\packages:/home/app/.nuget/packages"
    - "G:\\DEV\\repos\\RankingForum\\UserService:/app:rw"
    - "G:\\DEV\\repos\\RankingForum:/src:rw"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2024.1.2\\Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.1.2\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Wessel van Hemert\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\\
      DebuggerWorker\\JetBrains.Debugger.Worker.2024_5_20_03_19_20:/var/opt/rider-debugger:rw"
    working_dir: "/app"
