name: Run Unit Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore UserService dependencies
      run: dotnet restore UserServiceUnitTest/UserServiceUnitTest.csproj

    - name: Run UserService unit tests
      run: dotnet test UserServiceUnitTest/UserServiceUnitTest.csproj

  lint:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - name: Lint Code Base
         uses: github/super-linter@v6
         env:
           VALIDATE_ALL_CODEBASE: false
           VALIDATE_CSS: false
           DEFAULT_BRANCH: "main"
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           IGNORE_GITIGNORED_FILES: true
           VALIDATE_GITHUB_ACTIONS: false