name: CI/CD Deploy to Linode

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore UserService dependencies
      run: dotnet restore UserServiceUnitTest/UserServiceUnitTest.csproj

    - name: Run UserService unit tests
      run: dotnet test UserServiceUnitTest/UserServiceUnitTest.csproj
